// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Arm(arg1, arg2) {
  return window['go']['main']['App']['Arm'](arg1, arg2);
}

export function AskLocation() {
  return window['go']['main']['App']['AskLocation']();
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function Doctor() {
  return window['go']['main']['App']['Doctor']();
}

export function HelperInstalled() {
  return window['go']['main']['App']['HelperInstalled']();
}

export function Networks() {
  return window['go']['main']['App']['Networks']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Rejoin(arg1) {
  return window['go']['main']['App']['Rejoin'](arg1);
}

export function Release() {
  return window['go']['main']['App']['Release']();
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function Trust(arg1) {
  return window['go']['main']['App']['Trust'](arg1);
}

export function Untrust(arg1) {
  return window['go']['main']['App']['Untrust'](arg1);
}

export function UseVPN(arg1) {
  return window['go']['main']['App']['UseVPN'](arg1);
}
