// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Arm(arg1:string,arg2:string):Promise<void>;

export function AskLocation():Promise<void>;

export function Cancel():Promise<void>;

export function CancelHold():Promise<boolean>;

export function Doctor():Promise<Array<Record<string, any>>>;

export function HelperInstalled():Promise<boolean>;

export function Networks():Promise<main.Scan>;

export function Open(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Rejoin(arg1:string):Promise<void>;

export function Release():Promise<void>;

export function Settings():Promise<Record<string, any>>;

export function Trust(arg1:string):Promise<void>;

export function Untrust(arg1:string):Promise<void>;

export function UseVPN(arg1:string):Promise<void>;
