// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Arm() {
  return window['go']['main']['App']['Arm']();
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function Doctor() {
  return window['go']['main']['App']['Doctor']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}
