// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Arm():Promise<void>;

export function Cancel():Promise<void>;

export function Doctor():Promise<Array<Record<string, any>>>;

export function Open(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;
