// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Arm(arg1:string,arg2:string):Promise<void>;

export function AskLocation():Promise<void>;

export function Cancel():Promise<void>;

export function Doctor():Promise<Array<Record<string, any>>>;

export function Networks():Promise<main.Scan>;

export function Open(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;
